
// ===============================================================================
// BUSINESS DQ ASSISTANT -- Phase 1.6
// Clipboard-mediated AI workflow: prompt assembly -> copy -> paste -> parse -> commit
// Reference: TASK_G_ASSISTANT.md, PROMPT_SPEC_ASSISTANT.md
// ===============================================================================

const ASSISTANT_STORAGE_KEY = 'moj_dq_assistant_v1';
const PROMPT_VERSION        = 'BRA-2';

// ===============================================================================
// G1.2 -- STORAGE
// ===============================================================================

function loadAssistantState() {
  try {
    const raw = localStorage.getItem(ASSISTANT_STORAGE_KEY);
    if (!raw) return null;
    const s = JSON.parse(raw);
    return {
      rule_intent:       s.rule_intent       || '',
      cde_ids:           s.cde_ids           || [],
      extra_table_ids:   s.extra_table_ids   || [],
      conversation_mode: s.conversation_mode || 'business',
      proposals:         s.proposals         || [],
      saved_at:          s.saved_at          || null,
    };
  } catch { return null; }
}

function saveAssistantState(state) {
  try {
    localStorage.setItem(ASSISTANT_STORAGE_KEY, JSON.stringify({
      rule_intent:       state.rule_intent       || '',
      cde_ids:           state.cde_ids           || [],
      extra_table_ids:   state.extra_table_ids   || [],
      conversation_mode: state.conversation_mode || 'business',
      proposals:         state.proposals         || [],
      saved_at:          new Date().toISOString(),
    }));
    window.dispatchEvent(new Event('storage'));
  } catch {}
}

function clearAssistantState() {
  try {
    localStorage.removeItem(ASSISTANT_STORAGE_KEY);
    window.dispatchEvent(new Event('storage'));
  } catch {}
}

// ===============================================================================
// G1.3 -- CDE SUGGESTION MATCHING
// ===============================================================================

function suggestCdes(ruleIntentText, data) {
  if (!ruleIntentText || !data) return [];
  const cdes = (data.critical_data_element || []).filter(c => !c.retiring_timestamp);
  const tokens = ruleIntentText.toLowerCase().split(/[^a-z]+/).filter(t => t.length >= 3);
  if (tokens.length === 0) return [];
  const scored = cdes.map(cde => {
    const hay = [
      cde.source_field_name        || '',
      cde.source_table_name        || '',
      cde.source_system_name       || '',
      cde.source_database_name     || '',
      cde.data_element_definition  || '',
      cde.data_element_explanation || '',
    ].join(' ').toLowerCase();
    const score = tokens.reduce((s, t) => s + (hay.includes(t) ? 1 : 0), 0);
    return { cde, score };
  });
  return scored
    .filter(s => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 8)
    .map(s => s.cde);
}

// ===============================================================================
// G2 -- PROMPT BUILDER
// ===============================================================================

function buildHeaderSection(conversationMode) {
  const mode = conversationMode === 'technical' ? 'TECHNICAL' : 'BUSINESS';
  return [
    'PROMPT_VERSION: ' + PROMPT_VERSION,
    'CONVERSATION_MODE: ' + mode,
    'Generated by: DQ Accelerator - Business DQ Assistant',
    '---',
    '',
  ].join('\n');
}

function buildRoleSection() {
  return [
    '## YOUR ROLE',
    '',
    'You are a specialist data quality analyst embedded in a UK public sector data governance programme.',
    'Your role is to help a data steward take a business rule they have described in everyday language',
    'and turn it into a precise, testable data quality rule that can be applied to their data.',
    '',
    'You have been given context about the relevant data fields, table structures, data profiling',
    'statistics, quality dimensions, and any rules already in place. Use this context throughout',
    'the conversation.',
    '',
    "The steward is the subject matter expert on the business meaning of the data. You are the",
    "expert on data quality rule patterns and implementation. Work together to arrive at a rule",
    "that accurately captures the steward's intent.",
    '',
    'Do not produce a rule proposal until you are confident you understand:',
    '- The exact condition that makes a record fail the rule',
    '- Which data field(s) the rule checks',
    '- Which quality dimension best describes this type of failure',
    "- A realistic pass threshold based on the profiling data or the steward's knowledge",
    '',
    'If you need information not present in the context provided, ask the steward directly.',
    '',
    '---',
    '',
  ].join('\n');
}

function buildConversationModeSection(conversationMode) {
  if (conversationMode === 'technical') {
    return [
      '## CONVERSATION MODE: TECHNICAL',
      '',
      'The steward is technically proficient and comfortable with SQL and database concepts.',
      '',
      'Throughout this conversation you may:',
      '- Discuss SQL patterns and implementation details directly',
      '- Show draft SQL to the steward and invite technical feedback',
      '- Use precise technical language where appropriate',
      '- Explain the rule in both business and technical terms',
      '',
      'Ask the steward to review and confirm the SQL before producing the final proposal.',
      '',
      '---',
      '',
    ].join('\n');
  }
  return [
    '## CONVERSATION MODE: BUSINESS',
    '',
    "You are speaking with a business professional. They are the expert on the data's meaning",
    'but are not expected to understand SQL or database technology.',
    '',
    'Throughout this conversation you must:',
    '- Use plain, everyday English at all times',
    '- Never write or show SQL code to the steward',
    "- Explain data quality concepts using examples from the steward's own domain",
    '- When you have understood the rule, describe it back precisely in business language before',
    '  confirming it with the steward',
    '- Propose the quality dimension in plain terms (e.g. "this is a completeness issue")',
    '- Discuss the pass threshold in business terms (e.g. "we would expect 99 in every 100',
    '  records to pass this check -- does that sound right?")',
    '',
    'You will generate SQL internally to implement the rule, but you will not show it during the',
    'conversation. It will appear only in the structured proposal block at the end.',
    '',
    '---',
    '',
  ].join('\n');
}

function buildRuleIntentSection(ruleIntent, selectedCdeIds, data) {
  const lines = [
    '## RULE TO FORMALISE',
    '',
    'The steward has described the following business rule in their own words:',
    '',
    '"' + ruleIntent + '"',
    '',
  ];
  const cdes = (data.critical_data_element || []).filter(c => !c.retiring_timestamp);
  if (selectedCdeIds && selectedCdeIds.length > 0) {
    lines.push('The steward believes this rule relates to the following data fields:');
    selectedCdeIds.forEach(id => {
      const cde = cdes.find(c => c.critical_data_element_id === id);
      if (cde) {
        lines.push('- ' + (cde.source_field_name || 'unknown') + ' (' + (cde.source_table_name || 'unknown') + ')');
      }
    });
  } else {
    lines.push('The steward has not identified a specific data field yet. As part of the conversation,');
    lines.push('help identify which field(s) this rule should apply to, then confirm with the steward.');
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  return lines.join('\n');
}

function buildCdeSection(selectedCdeIds, conversationMode, data) {
  const cdes = (data.critical_data_element || []).filter(c => !c.retiring_timestamp);
  const lines = [
    '## CONTEXT: DATA FIELDS IN SCOPE',
    '',
  ];
  if (selectedCdeIds && selectedCdeIds.length > 0) {
    selectedCdeIds.forEach(id => {
      const cde = cdes.find(c => c.critical_data_element_id === id);
      if (!cde) return;
      lines.push('### Field: ' + (cde.source_field_name || 'not specified'));
      lines.push('Table:           ' + (cde.source_table_name        || 'not specified'));
      lines.push('Database:        ' + (cde.source_database_name     || 'not specified'));
      lines.push('System:          ' + (cde.source_system_name       || 'not specified'));
      lines.push('Platform:        ' + (cde.source_platform_name     || 'not specified'));
      lines.push('Definition:      ' + (cde.data_element_definition  || 'not specified'));
      lines.push('Explanation:     ' + (cde.data_element_explanation || 'not specified'));
      lines.push('Snapshot filter: ' + (cde.source_snapshot_filter   || 'not specified'));
      lines.push('Internal ID:     ' + cde.critical_data_element_id);
      lines.push('');
    });
  } else {
    lines.push('### All registered data fields (identify the relevant one(s) during the conversation)');
    const rows = cdes.slice(0, 50);
    rows.forEach(cde => {
      lines.push(
        cde.critical_data_element_id + ' | ' +
        (cde.source_field_name    || '') + ' | ' +
        (cde.source_table_name    || '') + ' | ' +
        (cde.source_system_name   || '')
      );
    });
    lines.push('');
  }
  lines.push('---');
  lines.push('');
  return lines.join('\n');
}

function buildSchemaSection(selectedCdeIds, extraTableIds, conversationMode, data) {
  const cdes  = (data.critical_data_element || []).filter(c => !c.retiring_timestamp);
  const ddls  = (data.source_table_ddl      || []).filter(d => !d.retiring_timestamp);
  const lines = ['## CONTEXT: TABLE STRUCTURE', ''];

  const primaryTableNames = new Set();
  if (selectedCdeIds && selectedCdeIds.length > 0) {
    selectedCdeIds.forEach(id => {
      const cde = cdes.find(c => c.critical_data_element_id === id);
      if (cde && cde.source_table_name) primaryTableNames.add(cde.source_table_name);
    });
  }

  const addedDdlIds = new Set();

  primaryTableNames.forEach(tblName => {
    const ddl = ddls.find(d => d.source_table_name === tblName);
    if (ddl) {
      addedDdlIds.add(ddl.source_table_ddl_id);
      const label = conversationMode === 'technical'
        ? '(primary -- referenced by selected CDE)'
        : '(contains the field in scope)';
      lines.push('### ' + tblName + ' ' + label);
      let cols = [];
      try { cols = ddl.parsed_columns ? JSON.parse(ddl.parsed_columns) : []; } catch {}
      if (cols.length > 0) {
        cols.forEach(c => { lines.push(c.name + '  ' + c.type); });
      } else if (ddl.ddl_text) {
        lines.push('[DDL text available but not yet parsed -- parse via Physical Layer screen]');
      }
      lines.push('');
    } else {
      lines.push('### ' + tblName + ' (contains the field in scope)');
      lines.push('No DDL registered. Add DDL via the Physical Layer screen to provide schema context.');
      lines.push('');
    }
  });

  if (extraTableIds && extraTableIds.length > 0) {
    extraTableIds.forEach(id => {
      const ddl = ddls.find(d => d.source_table_ddl_id === id);
      if (!ddl || addedDdlIds.has(id)) return;
      addedDdlIds.add(id);
      lines.push('### ' + ddl.source_table_name + ' (related table)');
      let cols = [];
      try { cols = ddl.parsed_columns ? JSON.parse(ddl.parsed_columns) : []; } catch {}
      if (cols.length > 0) {
        lines.push('Columns: ' + cols.map(c => c.name).join(', '));
      }
      lines.push('');
    });
  }

  if (primaryTableNames.size === 0 && (!extraTableIds || extraTableIds.length === 0)) {
    lines.push('No data fields selected and no supplementary tables added.');
    lines.push('Add CDEs or supplementary tables to include schema context.');
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  return lines.join('\n');
}

function buildProfilingSection(selectedCdeIds, data, compressed) {
  const cdes     = (data.critical_data_element || []).filter(c => !c.retiring_timestamp);
  const profiling = data.field_profiling || [];
  const lines    = ['## CONTEXT: DATA PROFILING', ''];

  if (!selectedCdeIds || selectedCdeIds.length === 0) {
    lines.push('No data fields selected. Profiling context is not available.');
    lines.push('');
    lines.push('---');
    lines.push('');
    return lines.join('\n');
  }

  const addedTables = new Set();
  let anyProfileFound = false;

  selectedCdeIds.forEach(id => {
    const cde = cdes.find(c => c.critical_data_element_id === id);
    if (!cde) return;
    const tblKey = (cde.source_database_name || '') + '|||' + (cde.source_table_name || '');
    if (addedTables.has(tblKey)) return;
    addedTables.add(tblKey);

    const tableProfiles = profiling.filter(p =>
      !p.retiring_timestamp &&
      p.source_database_name === cde.source_database_name &&
      p.source_table_name    === cde.source_table_name
    );

    lines.push('### ' + (cde.source_table_name || 'unknown'));
    if (tableProfiles.length === 0) {
      lines.push('No profiling data is available for this table yet. If statistics would help define');
      lines.push('a realistic threshold, ask the steward or capture profiling via the DDL screen.');
      lines.push('');
      return;
    }

    anyProfileFound = true;
    tableProfiles.forEach(p => {
      lines.push('Field: ' + (p.source_field_name || 'unknown'));
      if (p.summary_raw && !compressed) {
        lines.push(p.summary_raw);
      }
      if (!compressed && p.top_values_raw) {
        lines.push('Top values:');
        lines.push(p.top_values_raw);
      }
      if (!compressed && p.profiling_notes) {
        lines.push('Notes: ' + p.profiling_notes);
      }
      lines.push('');
    });
  });

  if (!anyProfileFound) {
    lines.push('No profiling data is available for the selected fields.');
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  return lines.join('\n');
}

function buildDimensionsSection(conversationMode, data) {
  const dims  = (data.quality_dimension || []).filter(d => !d.retiring_timestamp);
  const lines = [];

  if (conversationMode === 'technical') {
    lines.push('## CONTEXT: QUALITY DIMENSIONS');
    lines.push('');
  } else {
    lines.push('## CONTEXT: TYPES OF DATA QUALITY CHECK');
    lines.push('');
    lines.push('The following types of data quality check are used in this programme. Each rule you');
    lines.push('define will be categorised under one of these types. During the conversation,');
    lines.push('identify which type best describes the rule the steward has in mind.');
    lines.push('');
  }

  dims.forEach(d => {
    lines.push(d.quality_dimension_id + ' | ' + (d.dimension_name || '') +
      (d.dimension_acronymn ? ' (' + d.dimension_acronymn + ')' : ''));
  });

  lines.push('');
  lines.push('---');
  lines.push('');
  return lines.join('\n');
}

function buildExistingRulesSection(selectedCdeIds, conversationMode, data) {
  const allocs = data.data_quality_rule_allocation || [];
  const rules  = data.data_quality_rule            || [];
  const dims   = data.quality_dimension            || [];
  const lines  = [];

  let relevant = [];
  if (selectedCdeIds && selectedCdeIds.length > 0) {
    relevant = allocs.filter(a =>
      !a.retiring_timestamp &&
      selectedCdeIds.includes(a.critical_data_element_id)
    );
  }

  if (conversationMode === 'technical') {
    lines.push('## CONTEXT: EXISTING RULES ON THESE CDEs');
    lines.push('');
    if (relevant.length === 0) {
      lines.push('No rules are currently allocated to these CDEs.');
    } else {
      lines.push('The following rules are already in place. Do not reproduce these.');
      lines.push('');
      relevant.forEach(a => {
        const rule = rules.find(r => r.data_quality_rule_id === a.data_quality_rule_id);
        const dim  = dims.find(d => d.quality_dimension_id  === a.quality_dimension_id);
        if (!rule) return;
        lines.push('Rule: ' + rule.rule_name + ' | Dimension: ' + (dim ? dim.dimension_name : 'unknown'));
        if (rule.sql_code) {
          const sql = rule.sql_code.length > 200 ? rule.sql_code.substring(0, 200) + '...' : rule.sql_code;
          lines.push('SQL: ' + sql);
        }
        lines.push('---');
      });
    }
  } else {
    lines.push('## CONTEXT: EXISTING CHECKS ON THESE FIELDS');
    lines.push('');
    if (relevant.length === 0) {
      lines.push('No quality checks are currently registered for these fields.');
    } else {
      lines.push('The following data quality checks are already in place for these fields.');
      lines.push('Do not reproduce these. Identify new checks that complement the existing ones.');
      lines.push('');
      relevant.forEach(a => {
        const rule = rules.find(r => r.data_quality_rule_id === a.data_quality_rule_id);
        const dim  = dims.find(d => d.quality_dimension_id  === a.quality_dimension_id);
        if (!rule) return;
        lines.push('Check: ' + rule.rule_name + ' (' + (dim ? dim.dimension_name : 'unknown') + ')');
        if (rule.rule_explanation) lines.push('Description: ' + rule.rule_explanation);
        lines.push('---');
      });
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  return lines.join('\n');
}

function buildConversationInstructionsSection(conversationMode) {
  if (conversationMode === 'technical') {
    return [
      '## CONVERSATION INSTRUCTIONS',
      '',
      'Follow this process:',
      '',
      '1. Read the steward\'s rule description and the context carefully.',
      '2. Ask up to 3 targeted clarifying questions before drafting SQL. Focus on:',
      '   - The exact failure condition (null? wrong format? out of range? referential mismatch?)',
      '   - Whether the rule applies to all records or a subset',
      '   - How strict the threshold should be',
      '3. Identify the quality dimension and confirm with the steward.',
      '4. Draft the SQL rule. Show it to the steward and explain what it checks.',
      '   Ask for technical feedback and iterate if needed.',
      '5. Confirm the SQL and threshold before producing the formal proposal.',
      '6. Produce the rule proposal in the exact format below.',
      '',
      'You may produce multiple proposals if the steward\'s description implies more than one rule.',
      '',
      '---',
      '',
    ].join('\n');
  }
  return [
    '## CONVERSATION INSTRUCTIONS',
    '',
    'Follow this process carefully. The steward is a business expert, not a technical one.',
    'Your job is to translate their business knowledge into a precise quality rule.',
    '',
    'Step 1 -- Understand the rule intent',
    '  Ask up to 3 targeted clarifying questions to understand:',
    '  - What does a "bad" record look like? (missing value? wrong value? impossible value?)',
    '  - Does the rule apply to all records or only certain ones?',
    '  - Are there any known exceptions or edge cases?',
    '  Keep questions short and in plain language. Avoid technical jargon.',
    '',
    'Step 2 -- Identify the quality dimension',
    '  Tell the steward which type of data quality check this is (from the list above) and',
    '  explain in one sentence why. Confirm they agree before moving on.',
    '  Example: "This sounds like a Completeness issue -- we are checking that a required field',
    '  always has a value. Does that match your understanding?"',
    '',
    'Step 3 -- Confirm the rule in plain language',
    '  Write a precise, unambiguous description of the rule in plain English. This should be',
    '  specific enough that a colleague could apply it manually to a record.',
    '  Example: "Every prisoner record must have a date of birth recorded, and that date must',
    '  be in the past. Records where date of birth is blank, or where it falls on or after',
    '  today\'s date, will fail this check."',
    '  Ask the steward to confirm this accurately captures their intent.',
    '',
    'Step 4 -- Provide concrete examples',
    '  Give 2 to 3 specific examples of records that would FAIL this check.',
    '  Describe them in the steward\'s domain language, not database terms.',
    '  Example: "A prisoner record showing date of birth as 01/01/2040 would fail.',
    '  A record with no date of birth recorded would also fail."',
    '  Ask the steward to confirm these examples make sense.',
    '',
    'Step 5 -- Agree the pass threshold',
    '  Propose a pass threshold in business terms.',
    '  Example: "Based on the data profiling, around 2% of records currently have this issue.',
    '  Should we set the target so that 99 out of every 100 records must pass this check?',
    '  Or would you like a stricter target?"',
    '  Confirm the threshold with the steward.',
    '',
    'Step 6 -- Produce the proposal',
    '  Once the steward has confirmed the rule description, examples, and threshold, produce',
    '  the structured proposal in the format below. Generate the SQL internally without showing',
    '  it to the steward during the conversation.',
    '',
    'You may produce multiple proposals if the conversation reveals more than one distinct rule.',
    '',
    '---',
    '',
  ].join('\n');
}

function buildOutputFormatSection(conversationMode) {
  const intro = [
    '## OUTPUT FORMAT',
    '',
    'When you are ready to produce the formal rule proposal, output it in this exact format.',
    'Do not change the delimiter lines. Do not add text between START and END.',
    'You may produce multiple blocks if more than one rule was identified.',
    '',
  ];

  const block = [
    '===RULE_PROPOSAL_START===',
    '{',
    '  "rule_name": "Short descriptive name written for a business audience",',
    '  "rule_explanation": "Plain English explanation of what the rule checks and why it matters",',
    '  "rule_narrative": "Precise plain language statement of the rule confirmed with the steward",',
    '  "rule_examples": [',
    '    "Example of a record that would FAIL: [description]",',
    '    "Example of a record that would FAIL: [description]"',
    '  ],',
    '  "sql_code": "Full SQL implementing the rule -- must produce a pass rate between 0 and 1",',
    '  "sql_code_sample": "Optional: simplified SQL for technical reference",',
    '  "quality_dimension_id": 0,',
    '  "cde_id": 0,',
    '  "cde_suggestion": "If cde_id is null: field name and table you believe this applies to",',
    '  "bumper_value": 0.99,',
    '  "frequency": "daily",',
    '  "automated": true,',
    '  "steward_notes": "Any caveats, assumptions, or points for the steward to be aware of"',
    '}',
    '===RULE_PROPOSAL_END===',
  ];

  if (conversationMode !== 'technical') {
    return intro.concat([
      'Replace the placeholder values above with the actual values for this rule.',
      'quality_dimension_id must be an integer from the dimension list above.',
      'cde_id must be an integer from the data fields list above, or null if not pre-selected.',
      'bumper_value is a decimal between 0 and 1 (e.g. 0.99 means 99 in 100 records must pass).',
      '',
    ]).concat(block).join('\n');
  }
  return intro.concat(block).join('\n');
}

function buildAssistantPrompt(ruleIntent, selectedCdeIds, extraTableIds, conversationMode, data) {
  const mode = conversationMode || 'business';

  const sections = [
    buildHeaderSection(mode),
    buildRoleSection(),
    buildConversationModeSection(mode),
    buildRuleIntentSection(ruleIntent, selectedCdeIds, data),
    buildCdeSection(selectedCdeIds, mode, data),
    buildSchemaSection(selectedCdeIds, extraTableIds, mode, data),
    buildProfilingSection(selectedCdeIds, data, false),
    buildDimensionsSection(mode, data),
    buildExistingRulesSection(selectedCdeIds, mode, data),
    buildConversationInstructionsSection(mode),
    buildOutputFormatSection(mode),
  ];

  let promptText = sections.join('');
  const charCount = promptText.length;

  // Truncation: if over 6000 chars, rebuild with compressed profiling
  if (charCount > 6000) {
    const compressed = [
      buildHeaderSection(mode),
      buildRoleSection(),
      buildConversationModeSection(mode),
      buildRuleIntentSection(ruleIntent, selectedCdeIds, data),
      buildCdeSection(selectedCdeIds, mode, data),
      buildSchemaSection(selectedCdeIds, extraTableIds, mode, data),
      buildProfilingSection(selectedCdeIds, data, true),
      buildDimensionsSection(mode, data),
      buildExistingRulesSection(selectedCdeIds, mode, data),
      buildConversationInstructionsSection(mode),
      buildOutputFormatSection(mode),
    ].join('');
    if (compressed.length < charCount) promptText = compressed;
  }

  const finalCount = promptText.length;
  const truncated  = finalCount < charCount;

  // Context summary for UI display
  const selCdes = selectedCdeIds || [];
  const cdes    = (data.critical_data_element || []).filter(c => !c.retiring_timestamp);
  const tableNames = new Set();
  selCdes.forEach(id => {
    const cde = cdes.find(c => c.critical_data_element_id === id);
    if (cde && cde.source_table_name) tableNames.add(cde.source_table_name);
  });
  (extraTableIds || []).forEach(id => {
    const ddl = (data.source_table_ddl || []).find(d => d.source_table_ddl_id === id);
    if (ddl && ddl.source_table_name) tableNames.add(ddl.source_table_name);
  });

  const contextSummary = {
    cdeCount:           selCdes.length,
    tableCount:         tableNames.size,
    dimensionCount:     (data.quality_dimension || []).filter(d => !d.retiring_timestamp).length,
    truncated:          truncated,
    veryLarge:          finalCount > 10000,
    conversationMode:   mode,
    cdeNames:           selCdes.map(id => {
      const c = cdes.find(x => x.critical_data_element_id === id);
      return c ? (c.source_field_name + ' (' + c.source_table_name + ')') : ('ID ' + id);
    }),
    tableNamesList:     Array.from(tableNames),
    dimensionNames:     (data.quality_dimension || [])
      .filter(d => !d.retiring_timestamp)
      .map(d => d.dimension_name),
  };

  return { promptText, characterCount: finalCount, contextSummary };
}

// ===============================================================================
// G4.3 -- SUPPLEMENTARY CONTEXT PROMPT
// ===============================================================================

function buildSupplementaryPrompt(tableIds, data) {
  const ddls  = (data.source_table_ddl  || []).filter(d => !d.retiring_timestamp);
  const prof  = (data.field_profiling   || []).filter(p => !p.retiring_timestamp);
  const lines = [
    'SUPPLEMENTARY CONTEXT -- please incorporate into our ongoing conversation',
    '',
    'The steward has provided additional data structure information:',
    '',
  ];

  tableIds.forEach(id => {
    const ddl = ddls.find(d => d.source_table_ddl_id === id);
    if (!ddl) return;
    lines.push('### ' + ddl.source_table_name);
    let cols = [];
    try { cols = ddl.parsed_columns ? JSON.parse(ddl.parsed_columns) : []; } catch {}
    if (cols.length > 0) {
      cols.forEach(c => lines.push(c.name + '  ' + c.type));
    }
    lines.push('');
    const tableProf = prof.filter(p =>
      p.source_database_name === ddl.source_database_name &&
      p.source_table_name    === ddl.source_table_name
    );
    if (tableProf.length > 0) {
      lines.push('Data profiling for ' + ddl.source_table_name + ':');
      tableProf.forEach(p => {
        lines.push('Field: ' + (p.source_field_name || 'unknown'));
        if (p.summary_raw) lines.push(p.summary_raw);
        lines.push('');
      });
    }
  });

  lines.push('Please continue the conversation with this additional context in mind.');
  return lines.join('\n');
}

// ===============================================================================
// G4.4 -- REFINEMENT PROMPT
// ===============================================================================

function buildRefinementPrompt(proposal, gaps) {
  const lines = [
    'REFINEMENT REQUEST -- please update the rule proposal below',
    '',
    'The following issues were found with the rule proposal you produced:',
  ];
  gaps.forEach(g => lines.push('- ' + g));
  lines.push('');
  lines.push('Original proposal:');
  lines.push('===RULE_PROPOSAL_START===');
  lines.push(JSON.stringify(proposal, null, 2));
  lines.push('===RULE_PROPOSAL_END===');
  lines.push('');
  lines.push('Please address the issues above and produce a corrected proposal in the same format.');
  return lines.join('\n');
}

// ===============================================================================
// G3.2 -- CLIPBOARD
// ===============================================================================

function copyToClipboard(text, onSuccess, onFail) {
  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(text).then(onSuccess).catch(() => {
      fallbackCopy(text, onSuccess, onFail);
    });
  } else {
    fallbackCopy(text, onSuccess, onFail);
  }
}

function fallbackCopy(text, onSuccess, onFail) {
  try {
    const el = document.createElement('textarea');
    el.value = text;
    el.style.cssText = 'position:fixed;top:-9999px;left:-9999px';
    document.body.appendChild(el);
    el.select();
    const ok = document.execCommand('copy');
    document.body.removeChild(el);
    if (ok) onSuccess(); else onFail && onFail();
  } catch { onFail && onFail(); }
}

// ===============================================================================
// G4.2 -- PROPOSAL PARSER
// ===============================================================================

function parseProposals(text) {
  if (!text || !text.trim()) return { proposals: [], notFound: true };

  const startDelim = '===RULE_PROPOSAL_START===';
  const endDelim   = '===RULE_PROPOSAL_END===';

  const blocks = [];
  let searchFrom = 0;
  while (true) {
    const startIdx = text.indexOf(startDelim, searchFrom);
    if (startIdx === -1) break;
    const endIdx = text.indexOf(endDelim, startIdx + startDelim.length);
    if (endIdx === -1) break;
    blocks.push(text.substring(startIdx + startDelim.length, endIdx).trim());
    searchFrom = endIdx + endDelim.length;
  }

  if (blocks.length === 0) return { proposals: [], notFound: true };

  const proposals = [];
  const errors    = [];
  const now       = new Date().toISOString();

  blocks.forEach((block, i) => {
    try {
      const parsed = JSON.parse(block);
      proposals.push({
        ...parsed,
        parsed_at:  now,
        committed:  false,
      });
    } catch (e) {
      errors.push({ index: i, message: 'JSON parse error: ' + e.message, raw: block });
    }
  });

  // Version check
  let versionMismatch = false;
  const versionMatch = text.match(/PROMPT_VERSION:\s*(\S+)/);
  if (versionMatch && versionMatch[1] !== PROMPT_VERSION) {
    versionMismatch = true;
  }

  // Detect mode
  let detectedMode = null;
  const modeMatch = text.match(/CONVERSATION_MODE:\s*(\S+)/);
  if (modeMatch) detectedMode = modeMatch[1].toLowerCase();

  return { proposals, errors, versionMismatch, detectedMode };
}

// ===============================================================================
// G5.1 -- PROPOSAL VALIDATOR
// ===============================================================================

function validateProposal(proposal, data) {
  const gaps    = [];
  const staleIds = [];
  const warns   = [];

  if (!proposal.rule_name || !proposal.rule_name.trim()) {
    gaps.push('rule_name is missing');
  }
  if (!proposal.rule_narrative || !proposal.rule_narrative.trim()) {
    gaps.push('rule_narrative is missing (the plain language description of the rule)');
  }
  if (!proposal.sql_code || !proposal.sql_code.trim()) {
    gaps.push('sql_code is missing');
  } else if (!/select/i.test(proposal.sql_code)) {
    gaps.push('sql_code does not appear to contain a SELECT statement');
  }
  if (proposal.quality_dimension_id === undefined || proposal.quality_dimension_id === null) {
    gaps.push('quality_dimension_id is missing');
  }
  if (proposal.bumper_value === undefined || proposal.bumper_value === null) {
    gaps.push('bumper_value is missing');
  } else if (proposal.bumper_value < 0 || proposal.bumper_value > 1) {
    gaps.push('bumper_value must be between 0 and 1');
  }
  if (!proposal.frequency || !['daily','weekly','monthly'].includes(proposal.frequency)) {
    gaps.push('frequency must be one of: daily, weekly, monthly');
  }
  if (!proposal.cde_id && !proposal.cde_suggestion) {
    gaps.push('cde_id or cde_suggestion must be provided');
  }

  // Non-blocking warning for missing examples
  if (!proposal.rule_examples || !Array.isArray(proposal.rule_examples) || proposal.rule_examples.length === 0) {
    warns.push('rule_examples not provided -- the AI did not give examples of failing records');
  }

  // Stale ID checks
  if (proposal.quality_dimension_id) {
    const dims = data.quality_dimension || [];
    const found = dims.find(d =>
      d.quality_dimension_id === proposal.quality_dimension_id && !d.retiring_timestamp
    );
    if (!found) {
      staleIds.push('quality_dimension_id ' + proposal.quality_dimension_id + ' not found in current store');
    }
  }
  if (proposal.cde_id) {
    const cdes = data.critical_data_element || [];
    const found = cdes.find(c =>
      c.critical_data_element_id === proposal.cde_id && !c.retiring_timestamp
    );
    if (!found) {
      staleIds.push('cde_id ' + proposal.cde_id + ' not found in current store (may be retired or unknown)');
    }
  }

  return {
    valid:    gaps.length === 0,
    gaps,
    staleIds,
    warns,
  };
}

// ===============================================================================
// G1.5 -- STAGE INDICATOR
// ===============================================================================

function StageIndicator({ stage, onNavigateStage }) {
  const stages = [
    { n: 1, label: 'Define' },
    { n: 2, label: 'Prompt' },
    { n: 3, label: 'Paste'  },
    { n: 4, label: 'Commit' },
  ];
  return (
    <div style={{ display:'flex', alignItems:'center', gap:0, marginBottom:28 }}>
      {stages.map((s, i) => {
        const done    = s.n < stage;
        const active  = s.n === stage;
        const clickable = done;
        return (
          <React.Fragment key={s.n}>
            <div
              onClick={() => clickable && onNavigateStage(s.n)}
              style={{
                display:'flex', alignItems:'center', gap:6,
                padding:'6px 14px',
                borderRadius:'var(--radius)',
                cursor: clickable ? 'pointer' : 'default',
                background: active ? 'rgba(24,180,212,0.1)' : 'transparent',
                border: active ? '1px solid var(--accent)' : '1px solid transparent',
                transition:'all 0.15s',
              }}
            >
              <div style={{
                width:22, height:22, borderRadius:'50%', flexShrink:0,
                display:'flex', alignItems:'center', justifyContent:'center',
                fontSize:11, fontWeight:600, fontFamily:'var(--mono)',
                background: done ? 'var(--green-bg)' : active ? 'var(--accent)' : 'var(--bg3)',
                color: done ? 'var(--green)' : active ? '#fff' : 'var(--text3)',
                border: done ? '1px solid var(--green)' : active ? 'none' : '1px solid var(--border)',
              }}>
                {done ? <Icon.Check/> : s.n}
              </div>
              <span style={{
                fontSize:13,
                fontWeight: active ? 500 : 400,
                color: done ? 'var(--green)' : active ? 'var(--accent)' : 'var(--text3)',
                whiteSpace:'nowrap',
              }}>
                {s.label}
              </span>
            </div>
            {i < stages.length - 1 && (
              <div style={{
                flex:1, height:1, minWidth:16,
                background: s.n < stage ? 'var(--green)' : 'var(--border)',
                opacity: s.n < stage ? 0.5 : 1,
              }}/>
            )}
          </React.Fragment>
        );
      })}
    </div>
  );
}

// ===============================================================================
// MODE TOGGLE (Business / Technical)
// ===============================================================================

function ModeToggle({ mode, onChange, promptBuilt }) {
  return (
    <div style={{ marginBottom:20 }}>
      <div style={{ fontSize:11, fontWeight:600, letterSpacing:'0.1em', textTransform:'uppercase',
        color:'var(--text3)', marginBottom:8 }}>
        Conversation Mode
      </div>
      <div style={{ display:'flex', gap:8 }}>
        {[
          { val:'business',  label:'Business',  sub:'Plain language -- no SQL shown' },
          { val:'technical', label:'Technical', sub:'SQL discussion included' },
        ].map(opt => (
          <div key={opt.val}
            onClick={() => onChange(opt.val)}
            style={{
              flex:1, padding:'10px 14px', cursor:'pointer', borderRadius:'var(--radius)',
              border: mode === opt.val ? '1px solid var(--accent)' : '1px solid var(--border)',
              background: mode === opt.val ? 'rgba(24,180,212,0.08)' : 'var(--bg3)',
              transition:'all 0.15s',
            }}>
            <div style={{ fontWeight:500, fontSize:13,
              color: mode === opt.val ? 'var(--accent)' : 'var(--text2)' }}>
              {opt.val === mode && <span style={{ marginRight:5 }}>&#10003;</span>}
              {opt.label}
            </div>
            <div style={{ fontSize:11, color:'var(--text3)', marginTop:2 }}>{opt.sub}</div>
          </div>
        ))}
      </div>
      {promptBuilt && (
        <div style={{ fontSize:11, color:'var(--amber)', marginTop:6 }}>
          Mode changed -- rebuild the prompt to apply this change.
        </div>
      )}
    </div>
  );
}

// ===============================================================================
// G1.4 -- STAGE 1 PANEL
// ===============================================================================

function Stage1Panel({
  conversationMode, onModeChange,
  ruleIntent, onRuleIntentChange,
  selectedCdeIds, onCdeToggle,
  extraTableIds, onExtraTableToggle,
  suggestions, cdeSearch, onCdeSearch,
  data, onBuild, promptBuilt,
}) {
  const [showSupp, setShowSupp] = useState(false);

  const cdes     = (data.critical_data_element || []).filter(c => !c.retiring_timestamp);
  const ddls     = (data.source_table_ddl      || []).filter(d => !d.retiring_timestamp);
  const cdeSrch  = cdeSearch.toLowerCase();

  // Tables already covered by selected CDEs
  const coveredTables = new Set(
    selectedCdeIds.map(id => {
      const cde = cdes.find(c => c.critical_data_element_id === id);
      return cde ? cde.source_table_name : null;
    }).filter(Boolean)
  );

  const suppTables = ddls.filter(d => !coveredTables.has(d.source_table_name));

  const filteredCdes = cdeSrch.length > 0
    ? cdes.filter(c =>
        (c.source_field_name    || '').toLowerCase().includes(cdeSrch) ||
        (c.source_table_name    || '').toLowerCase().includes(cdeSrch) ||
        (c.source_system_name   || '').toLowerCase().includes(cdeSrch) ||
        (c.source_database_name || '').toLowerCase().includes(cdeSrch)
      )
    : cdes.slice(0, 30);

  const inputStyle = {
    width:'100%', padding:'8px 11px', fontSize:13,
    background:'var(--bg3)', border:'1px solid var(--border)',
    borderRadius:'var(--radius)', color:'var(--text)',
    fontFamily:'var(--sans)', outline:'none', resize:'vertical',
  };

  const selSet = new Set(selectedCdeIds);

  return (
    <div>
      <ModeToggle mode={conversationMode} onChange={onModeChange} promptBuilt={promptBuilt}/>

      {/* Rule intent textarea */}
      <div style={{ marginBottom:16 }}>
        <label style={{ display:'block', fontSize:12, fontWeight:600,
          color:'var(--text2)', marginBottom:6, textTransform:'uppercase', letterSpacing:'0.08em' }}>
          Describe the rule
        </label>
        <textarea
          value={ruleIntent}
          onChange={e => onRuleIntentChange(e.target.value)}
          rows={5}
          placeholder="e.g. Every offender record must have a valid date of birth and it must not be in the future"
          style={{ ...inputStyle, minHeight:100 }}
        />
      </div>

      {/* CDE suggestion chips */}
      {suggestions.length > 0 && (
        <div style={{ marginBottom:12 }}>
          <div style={{ fontSize:11, color:'var(--text3)', marginBottom:6 }}>
            Suggested fields -- click to add:
          </div>
          <div style={{ display:'flex', flexWrap:'wrap', gap:6 }}>
            {suggestions.slice(0,5).map(cde => {
              const alreadySelected = selSet.has(cde.critical_data_element_id);
              if (alreadySelected) return null;
              return (
                <span key={cde.critical_data_element_id}
                  onClick={() => onCdeToggle(cde.critical_data_element_id)}
                  style={{
                    padding:'3px 10px', borderRadius:20, cursor:'pointer', fontSize:12,
                    background:'rgba(24,180,212,0.1)', color:'var(--accent)',
                    border:'1px solid rgba(24,180,212,0.3)',
                  }}>
                  {cde.source_field_name}.{cde.source_table_name}
                </span>
              );
            })}
          </div>
        </div>
      )}

      {/* Selected CDEs */}
      {selectedCdeIds.length > 0 && (
        <div style={{ marginBottom:12 }}>
          <div style={{ fontSize:11, color:'var(--text3)', marginBottom:6 }}>Selected fields:</div>
          <div style={{ display:'flex', flexWrap:'wrap', gap:6 }}>
            {selectedCdeIds.map(id => {
              const cde = cdes.find(c => c.critical_data_element_id === id);
              if (!cde) return null;
              return (
                <span key={id} style={{
                  padding:'3px 10px', borderRadius:20, fontSize:12,
                  background:'var(--green-bg)', color:'var(--green)',
                  border:'1px solid var(--green)',
                  display:'flex', alignItems:'center', gap:6,
                }}>
                  {cde.source_field_name}.{cde.source_table_name}
                  <span onClick={() => onCdeToggle(id)}
                    style={{ cursor:'pointer', opacity:0.7, display:'flex', width:14, height:14, flexShrink:0 }}>
                    <Icon.X/>
                  </span>
                </span>
              );
            })}
          </div>
        </div>
      )}

      {/* CDE search */}
      <div style={{ marginBottom:16 }}>
        <div style={{ fontSize:11, color:'var(--text3)', marginBottom:6,
          display:'flex', alignItems:'center', gap:5 }}>
          <span style={{ width:13, height:13, display:'flex', alignItems:'center',
            justifyContent:'center', flexShrink:0 }}><Icon.Search/></span>
          Search data fields (optional -- leave blank to let the AI suggest):
        </div>
        <input
          type="text"
          value={cdeSearch}
          onChange={e => onCdeSearch(e.target.value)}
          placeholder="field name, table, system..."
          style={{ ...inputStyle, resize:'none' }}
        />
        {(cdeSrch.length > 0 || cdes.length <= 30) && (
          <div style={{
            maxHeight:160, overflowY:'auto', marginTop:4,
            border:'1px solid var(--border)', borderRadius:'var(--radius)',
            background:'var(--bg3)',
          }}>
            {filteredCdes.length === 0 && (
              <div style={{ padding:'8px 12px', fontSize:12, color:'var(--text3)' }}>No fields match</div>
            )}
            {filteredCdes.map(cde => {
              const sel = selSet.has(cde.critical_data_element_id);
              return (
                <div key={cde.critical_data_element_id}
                  onClick={() => onCdeToggle(cde.critical_data_element_id)}
                  style={{
                    padding:'6px 12px', cursor:'pointer', fontSize:12,
                    background: sel ? 'var(--green-bg)' : 'transparent',
                    color: sel ? 'var(--green)' : 'var(--text2)',
                    borderBottom:'1px solid var(--border)',
                    display:'flex', justifyContent:'space-between',
                  }}>
                  <span>{cde.source_field_name} <span style={{ color:'var(--text3)' }}>({cde.source_table_name})</span></span>
                  {sel && <span style={{ width:14, height:14, display:'flex', alignItems:'center', flexShrink:0 }}><Icon.Check/></span>}
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Supplementary tables */}
      <div style={{ marginBottom:20 }}>
        <div
          onClick={() => setShowSupp(v => !v)}
          style={{ cursor:'pointer', fontSize:12, color:'var(--text3)',
            display:'flex', alignItems:'center', gap:6 }}>
          <span style={{ transform: showSupp ? 'rotate(90deg)' : 'none',
            display:'inline-block', transition:'transform 0.15s' }}>&#9658;</span>
          Add more context (supplementary tables not covered by selected CDEs)
          {extraTableIds.length > 0 && (
            <span className="badge badge-blue">{extraTableIds.length} added</span>
          )}
        </div>
        {showSupp && (
          <div style={{ marginTop:10, paddingLeft:16 }}>
            {suppTables.length === 0
              ? <div style={{ fontSize:12, color:'var(--text3)' }}>
                  No additional tables available (all DDL tables are already covered by selected CDEs,
                  or no DDL has been registered yet).
                </div>
              : suppTables.map(ddl => {
                  const sel = extraTableIds.includes(ddl.source_table_ddl_id);
                  return (
                    <div key={ddl.source_table_ddl_id}
                      onClick={() => onExtraTableToggle(ddl.source_table_ddl_id)}
                      style={{ display:'flex', alignItems:'center', gap:8,
                        padding:'5px 0', cursor:'pointer', fontSize:13 }}>
                      <input type="checkbox" readOnly checked={sel}
                        style={{ cursor:'pointer' }}/>
                      <span style={{ color: sel ? 'var(--text)' : 'var(--text2)' }}>
                        {ddl.source_table_name}
                        <span style={{ color:'var(--text3)', fontSize:11, marginLeft:6 }}>
                          {ddl.source_database_name}
                        </span>
                      </span>
                    </div>
                  );
                })
            }
          </div>
        )}
      </div>

      {/* Build button */}
      <div style={{ display:'flex', alignItems:'center', gap:16 }}>
        <button
          className="btn btn-primary"
          disabled={!ruleIntent || ruleIntent.trim().length < 10}
          onClick={onBuild}
          style={{ fontSize:14 }}>
          <Icon.Sparkle/> Build prompt
        </button>
        <span style={{ fontSize:12, color:'var(--text3)' }}>
          {selectedCdeIds.length > 0
            ? selectedCdeIds.length + ' field(s) selected'
            : 'No fields selected -- the AI will identify them'}
        </span>
      </div>
    </div>
  );
}

// ===============================================================================
// G3.1 -- STAGE 2 PANEL
// ===============================================================================

function Stage2Panel({ builtPrompt, contextSummary, onCopy, copyConfirmed, onBack }) {
  const [showDetails, setShowDetails] = useState(false);

  if (!builtPrompt) return null;

  const { cdeCount, tableCount, dimensionCount, characterCount: cc, truncated, veryLarge,
    cdeNames, tableNamesList, dimensionNames } = contextSummary;
  const charCount = builtPrompt.length;

  return (
    <div>
      {/* Context summary strip */}
      <div style={{ display:'flex', flexWrap:'wrap', gap:8, marginBottom:16 }}>
        <span className="badge badge-blue">{cdeCount} field{cdeCount !== 1 ? 's' : ''}</span>
        <span className="badge badge-blue">{tableCount} table{tableCount !== 1 ? 's' : ''}</span>
        <span className="badge badge-blue">{dimensionCount} quality dimensions</span>
        <span className="badge badge-gray">~{charCount.toLocaleString()} chars</span>
        {truncated && <span className="badge badge-amber">Context compressed</span>}
        {contextSummary.conversationMode === 'business'
          ? <span className="badge badge-gray">Business mode</span>
          : <span className="badge badge-gray">Technical mode</span>
        }
      </div>

      {veryLarge && (
        <div className="status-row status-warn" style={{ marginBottom:16 }}>
          <Icon.Warning/>
          This prompt is large (~{charCount.toLocaleString()} chars). Verify your AI tool supports this input size.
        </div>
      )}

      {/* What is in this prompt */}
      <div style={{ marginBottom:16 }}>
        <div onClick={() => setShowDetails(v => !v)}
          style={{ cursor:'pointer', fontSize:12, color:'var(--text3)',
            display:'flex', alignItems:'center', gap:6 }}>
          <span style={{ transform: showDetails ? 'rotate(90deg)' : 'none',
            display:'inline-block', transition:'transform 0.15s' }}>&#9658;</span>
          What is in this prompt?
        </div>
        {showDetails && (
          <div style={{ marginTop:8, padding:'12px 16px',
            background:'var(--bg3)', borderRadius:'var(--radius)',
            fontSize:12, color:'var(--text2)', lineHeight:1.8 }}>
            {cdeNames.length > 0 && (
              <div><strong>Fields:</strong> {cdeNames.join(', ')}</div>
            )}
            {tableNamesList.length > 0 && (
              <div><strong>Tables:</strong> {tableNamesList.join(', ')}</div>
            )}
            {dimensionNames.length > 0 && (
              <div><strong>Quality dimensions:</strong> {dimensionNames.join(', ')}</div>
            )}
            {cdeNames.length === 0 && (
              <div style={{ color:'var(--text3)' }}>
                No specific fields selected -- the AI will help identify the relevant field.
              </div>
            )}
          </div>
        )}
      </div>

      {/* Prompt textarea */}
      <textarea
        readOnly
        value={builtPrompt}
        rows={16}
        style={{
          width:'100%', padding:'12px', fontSize:12,
          fontFamily:'var(--mono)', background:'var(--bg)',
          border:'1px solid var(--border)', borderRadius:'var(--radius)',
          color:'var(--text2)', resize:'vertical', marginBottom:12, outline:'none',
        }}
      />

      {/* Copy button */}
      <div style={{ display:'flex', alignItems:'center', gap:16, marginBottom:8 }}>
        <button className={copyConfirmed ? 'btn btn-green' : 'btn btn-primary'}
          onClick={onCopy} style={{ fontSize:14 }}>
          <Icon.Copy/>
          {copyConfirmed ? 'Copied!' : 'Copy to clipboard'}
        </button>
        <button className="btn btn-ghost" onClick={onBack}>
          Edit scope
        </button>
      </div>

      {copyConfirmed && (
        <div style={{ fontSize:12, color:'var(--text3)', marginTop:4 }}>
          Paste this into your AI assistant. Come back here when it has produced a rule proposal.
        </div>
      )}
    </div>
  );
}

// ===============================================================================
// G4.1 -- STAGE 3 PANEL
// ===============================================================================

function Stage3Panel({
  pasteText, onPasteChange, onParse, parseResult,
  onAddContextCopy, data, extraTableIds, onExtraTableToggle,
  onRegeneratePrompt,
}) {
  const [showAddCtx, setShowAddCtx] = useState(false);
  const [suppSel,    setSuppSel]    = useState([]);
  const ddls = (data.source_table_ddl || []).filter(d => !d.retiring_timestamp);

  return (
    <div>
      <p style={{ fontSize:13, color:'var(--text2)', marginBottom:14, lineHeight:1.7 }}>
        Paste your AI assistant output below. You can paste the full conversation transcript --
        the parser will extract the rule proposal automatically.
      </p>

      <textarea
        value={pasteText}
        onChange={e => onPasteChange(e.target.value)}
        rows={10}
        placeholder={'Paste the AI response or full conversation transcript here...'}
        style={{
          width:'100%', padding:'12px', fontSize:12,
          fontFamily:'var(--mono)', background:'var(--bg3)',
          border:'1px solid var(--border)', borderRadius:'var(--radius)',
          color:'var(--text)', resize:'vertical', marginBottom:12, outline:'none',
        }}
      />

      <div style={{ display:'flex', gap:10, marginBottom:16 }}>
        <button className="btn btn-primary" onClick={onParse}
          disabled={!pasteText || !pasteText.trim()}>
          Parse result
        </button>
        <button className="btn btn-ghost" onClick={onRegeneratePrompt}>
          Re-generate prompt
        </button>
      </div>

      {/* Parse result status */}
      {parseResult && (
        <div style={{ marginBottom:16 }}>
          {parseResult.notFound && (
            <div className="status-row status-err">
              <Icon.Warning/>
              No rule proposal found. The AI output should contain lines like:
              <span style={{ fontFamily:'var(--mono)', marginLeft:6 }}>===RULE_PROPOSAL_START===</span>
            </div>
          )}
          {parseResult.proposals && parseResult.proposals.length > 0 && (
            <div className="status-row status-ok">
              <Icon.Check/>
              {parseResult.proposals.length} proposal{parseResult.proposals.length !== 1 ? 's' : ''} found -- scroll down to review.
            </div>
          )}
          {parseResult.errors && parseResult.errors.length > 0 && (
            <div className="status-row status-warn" style={{ marginTop:6 }}>
              <Icon.Warning/>
              {parseResult.errors.length} block{parseResult.errors.length !== 1 ? 's' : ''} could not be parsed (JSON error). Check the AI output format.
            </div>
          )}
          {parseResult.versionMismatch && (
            <div className="status-row status-warn" style={{ marginTop:6 }}>
              <Icon.Warning/>
              Prompt version mismatch. The AI may have used an older prompt -- review the proposal carefully.
            </div>
          )}
        </div>
      )}

      {/* Add context */}
      <div style={{ borderTop:'1px solid var(--border)', paddingTop:14, marginTop:8 }}>
        <div onClick={() => setShowAddCtx(v => !v)}
          style={{ cursor:'pointer', fontSize:12, color:'var(--text3)',
            display:'flex', alignItems:'center', gap:6 }}>
          <span style={{ transform: showAddCtx ? 'rotate(90deg)' : 'none',
            display:'inline-block', transition:'transform 0.15s' }}>&#9658;</span>
          AI needs more information? Add supplementary context
        </div>
        {showAddCtx && (
          <div style={{ marginTop:10 }}>
            <div style={{ fontSize:12, color:'var(--text2)', marginBottom:8 }}>
              Select additional tables to include and copy a short supplementary prompt:
            </div>
            {ddls.length === 0
              ? <div style={{ fontSize:12, color:'var(--text3)' }}>
                  No DDL tables registered. Add DDL via Physical Layer to enable this.
                </div>
              : ddls.map(ddl => {
                  const sel = suppSel.includes(ddl.source_table_ddl_id);
                  return (
                    <div key={ddl.source_table_ddl_id}
                      onClick={() => setSuppSel(prev =>
                        sel ? prev.filter(x => x !== ddl.source_table_ddl_id)
                            : [...prev, ddl.source_table_ddl_id]
                      )}
                      style={{ display:'flex', alignItems:'center', gap:8,
                        padding:'4px 0', cursor:'pointer', fontSize:13 }}>
                      <input type="checkbox" readOnly checked={sel} style={{ cursor:'pointer' }}/>
                      <span style={{ color: sel ? 'var(--text)' : 'var(--text2)' }}>
                        {ddl.source_table_name}
                      </span>
                    </div>
                  );
                })
            }
            {suppSel.length > 0 && (
              <button className="btn btn-ghost" style={{ marginTop:10 }}
                onClick={() => onAddContextCopy(suppSel)}>
                <Icon.Copy/> Copy supplementary prompt
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ===============================================================================
// G6.2 -- PROPOSAL REVIEW CARD
// ===============================================================================

function ProposalReviewCard({ proposal, index, validation, onCommit, onRefine, onUpdate, onDiscard, data }) {
  const dims   = (data.quality_dimension     || []).filter(d => !d.retiring_timestamp);
  const cdes   = (data.critical_data_element || []).filter(c => !c.retiring_timestamp);

  const [local, setLocal] = useState(() => ({ ...proposal }));
  const [showTech, setShowTech] = useState(false);
  const [committing, setCommitting] = useState(false);
  const [commitError, setCommitError] = useState('');

  const update = (field, val) => {
    const next = { ...local, [field]: val };
    setLocal(next);
    onUpdate(index, next);
  };

  const liveValidation = validateProposal(local, data);
  const canCommit = liveValidation.valid && !!local.cde_id;

  const inputStyle = {
    width:'100%', padding:'7px 10px', fontSize:13,
    background:'var(--bg3)', border:'1px solid var(--border)',
    borderRadius:'var(--radius)', color:'var(--text)',
    fontFamily:'var(--sans)', outline:'none',
  };
  const monoStyle = { ...inputStyle, fontFamily:'var(--mono)', fontSize:12 };

  if (proposal.committed) {
    return (
      <div className="card" style={{ borderColor:'var(--green)', marginBottom:16 }}>
        <div style={{ display:'flex', alignItems:'center', gap:10 }}>
          <span className="badge badge-green">Committed</span>
          <span style={{ fontWeight:600, fontSize:14 }}>{proposal.rule_name}</span>
        </div>
        {proposal._createdRuleId && (
          <div style={{ fontSize:12, color:'var(--text3)', marginTop:8 }}>
            Rule ID: {proposal._createdRuleId} &nbsp;|&nbsp;
            Allocation ID: {proposal._createdAllocId}
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="card" style={{ marginBottom:20,
      borderColor: commitError ? 'var(--red)' : 'var(--border)' }}>

      {/* Card header */}
      <div style={{ display:'flex', alignItems:'center', gap:10, marginBottom:16 }}>
        <span className="badge badge-blue">Proposal {index + 1}</span>
        {liveValidation.valid
          ? <span className="badge badge-green">Ready to commit</span>
          : <span className="badge badge-amber">{liveValidation.gaps.length} issue{liveValidation.gaps.length !== 1 ? 's' : ''}</span>
        }
      </div>

      {/* ---- BUSINESS REVIEW SECTION ---- */}
      <div style={{ fontSize:10, fontWeight:600, letterSpacing:'0.1em', textTransform:'uppercase',
        color:'var(--text3)', marginBottom:14, borderBottom:'1px solid var(--border)', paddingBottom:6 }}>
        Business Review
      </div>

      {/* Rule name */}
      <div style={{ marginBottom:12 }}>
        <label style={{ display:'block', fontSize:11, color:'var(--text3)',
          marginBottom:4, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.08em' }}>
          Rule name *
        </label>
        <input type="text" value={local.rule_name || ''} onChange={e => update('rule_name', e.target.value)}
          style={inputStyle}/>
      </div>

      {/* Rule narrative */}
      <div style={{ marginBottom:12 }}>
        <label style={{ display:'block', fontSize:11, color:'var(--text3)',
          marginBottom:4, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.08em' }}>
          Rule description (plain language) *
        </label>
        <textarea value={local.rule_narrative || ''} onChange={e => update('rule_narrative', e.target.value)}
          rows={3} style={{ ...inputStyle, resize:'vertical' }}/>
        <div style={{ fontSize:11, color:'var(--text3)', marginTop:2 }}>
          This is the primary statement of what the rule checks, confirmed with the steward.
        </div>
      </div>

      {/* Rule examples */}
      {local.rule_examples && Array.isArray(local.rule_examples) && local.rule_examples.length > 0 && (
        <div style={{ marginBottom:12 }}>
          <div style={{ fontSize:11, color:'var(--text3)', fontWeight:600,
            textTransform:'uppercase', letterSpacing:'0.08em', marginBottom:6 }}>
            Examples of failing records
          </div>
          <ul style={{ paddingLeft:18, margin:0 }}>
            {local.rule_examples.map((ex, i) => (
              <li key={i} style={{ fontSize:13, color:'var(--text2)', marginBottom:4, lineHeight:1.5 }}>
                {ex}
              </li>
            ))}
          </ul>
        </div>
      )}
      {(!local.rule_examples || !Array.isArray(local.rule_examples) || local.rule_examples.length === 0) && (
        <div className="status-row status-warn" style={{ marginBottom:12 }}>
          <Icon.Warning/> The AI did not provide examples of failing records. Consider refining.
        </div>
      )}

      {/* Rule explanation */}
      <div style={{ marginBottom:12 }}>
        <label style={{ display:'block', fontSize:11, color:'var(--text3)',
          marginBottom:4, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.08em' }}>
          Additional explanation (optional)
        </label>
        <textarea value={local.rule_explanation || ''} onChange={e => update('rule_explanation', e.target.value)}
          rows={2} style={{ ...inputStyle, resize:'vertical' }}/>
      </div>

      {/* Quality dimension */}
      <div style={{ marginBottom:12 }}>
        <label style={{ display:'block', fontSize:11, color:'var(--text3)',
          marginBottom:4, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.08em' }}>
          Type of check *
        </label>
        <select value={local.quality_dimension_id || ''} onChange={e => update('quality_dimension_id', parseInt(e.target.value) || null)}
          style={{ ...inputStyle }}>
          <option value="">-- select --</option>
          {dims.map(d => (
            <option key={d.quality_dimension_id} value={d.quality_dimension_id}>{d.dimension_name}</option>
          ))}
        </select>
        {validation.staleIds.some(s => s.startsWith('quality_dimension_id')) && (
          <div style={{ fontSize:11, color:'var(--amber)', marginTop:3, display:'flex', alignItems:'center', gap:5 }}>
            <span style={{ width:13, height:13, display:'flex', alignItems:'center', flexShrink:0 }}><Icon.Warning/></span>
            The quality dimension ID from the AI no longer exists -- please re-select.
          </div>
        )}
      </div>

      {/* CDE */}
      <div style={{ marginBottom:12 }}>
        <label style={{ display:'block', fontSize:11, color:'var(--text3)',
          marginBottom:4, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.08em' }}>
          Data field *
        </label>
        {local.cde_suggestion && !local.cde_id && (
          <div style={{ fontSize:12, color:'var(--amber)', marginBottom:4 }}>
            AI suggested: "{local.cde_suggestion}" -- please select the matching field below.
          </div>
        )}
        <select value={local.cde_id || ''} onChange={e => update('cde_id', parseInt(e.target.value) || null)}
          style={{ ...inputStyle }}>
          <option value="">-- select --</option>
          {cdes.map(c => (
            <option key={c.critical_data_element_id} value={c.critical_data_element_id}>
              {c.source_field_name} ({c.source_table_name})
            </option>
          ))}
        </select>
        {validation.staleIds.some(s => s.startsWith('cde_id')) && (
          <div style={{ fontSize:11, color:'var(--amber)', marginTop:3, display:'flex', alignItems:'center', gap:5 }}>
            <span style={{ width:13, height:13, display:'flex', alignItems:'center', flexShrink:0 }}><Icon.Warning/></span>
            The CDE ID from the AI no longer exists -- please re-select.
          </div>
        )}
      </div>

      {/* Pass target + frequency */}
      <div style={{ display:'flex', gap:12, marginBottom:12 }}>
        <div style={{ flex:1 }}>
          <label style={{ display:'block', fontSize:11, color:'var(--text3)',
            marginBottom:4, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.08em' }}>
            Pass target *
          </label>
          <input type="number" min={0} max={1} step={0.01}
            value={local.bumper_value !== undefined && local.bumper_value !== null ? local.bumper_value : ''}
            onChange={e => update('bumper_value', parseFloat(e.target.value))}
            style={inputStyle}/>
          <div style={{ fontSize:11, color:'var(--text3)', marginTop:2 }}>
            0-1 (e.g. 0.99 = 99 in every 100 records must pass)
          </div>
        </div>
        <div style={{ flex:1 }}>
          <label style={{ display:'block', fontSize:11, color:'var(--text3)',
            marginBottom:4, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.08em' }}>
            Frequency *
          </label>
          <select value={local.frequency || ''} onChange={e => update('frequency', e.target.value)}
            style={inputStyle}>
            <option value="">-- select --</option>
            <option value="daily">Daily</option>
            <option value="weekly">Weekly</option>
            <option value="monthly">Monthly</option>
          </select>
        </div>
        <div style={{ flex:1 }}>
          <label style={{ display:'block', fontSize:11, color:'var(--text3)',
            marginBottom:4, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.08em' }}>
            Automated
          </label>
          <div style={{ display:'flex', alignItems:'center', gap:8, padding:'8px 0' }}>
            <label className="toggle">
              <input type="checkbox" checked={!!local.automated}
                onChange={e => update('automated', e.target.checked)}/>
              <span className="toggle-track"/>
              <span className="toggle-thumb"/>
            </label>
            <span className="toggle-label">{local.automated ? 'Yes' : 'No'}</span>
          </div>
        </div>
      </div>

      {/* Steward notes */}
      {local.steward_notes && (
        <div style={{ marginBottom:12, padding:'10px 12px',
          background:'var(--bg3)', borderRadius:'var(--radius)',
          borderLeft:'3px solid var(--accent)', fontSize:12, color:'var(--text2)' }}>
          <strong>AI notes:</strong> {local.steward_notes}
        </div>
      )}

      {/* ---- TECHNICAL DETAILS (collapsed) ---- */}
      <div style={{ borderTop:'1px solid var(--border)', paddingTop:12, marginTop:4 }}>
        <div onClick={() => setShowTech(v => !v)}
          style={{ cursor:'pointer', fontSize:12, color:'var(--text3)',
            display:'flex', alignItems:'center', gap:6 }}>
          <span style={{ transform: showTech ? 'rotate(90deg)' : 'none',
            display:'inline-block', transition:'transform 0.15s' }}>&#9658;</span>
          {showTech ? 'Hide technical details' : 'Show technical details (SQL)'}
        </div>

        {showTech && (
          <div style={{ marginTop:12 }}>
            <div style={{ marginBottom:12 }}>
              <label style={{ display:'block', fontSize:11, color:'var(--text3)',
                marginBottom:4, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.08em' }}>
                SQL rule *
              </label>
              <textarea value={local.sql_code || ''} onChange={e => update('sql_code', e.target.value)}
                rows={5} style={{ ...monoStyle, resize:'vertical' }}/>
            </div>
            <div style={{ marginBottom:4 }}>
              <label style={{ display:'block', fontSize:11, color:'var(--text3)',
                marginBottom:4, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.08em' }}>
                Simplified SQL (optional)
              </label>
              <textarea value={local.sql_code_sample || ''} onChange={e => update('sql_code_sample', e.target.value)}
                rows={3} style={{ ...monoStyle, resize:'vertical' }}/>
            </div>
          </div>
        )}
      </div>

      {/* Validation issues */}
      {liveValidation.gaps.length > 0 && (
        <div style={{ marginTop:12 }}>
          {liveValidation.gaps.map((g, i) => (
            <div key={i} style={{ fontSize:12, color:'var(--amber)', display:'flex', gap:6, alignItems:'flex-start', marginBottom:3 }}>
              <span style={{ width:14, height:14, display:'flex', alignItems:'center', flexShrink:0, marginTop:1 }}><Icon.Warning/></span>
              {g}
            </div>
          ))}
        </div>
      )}

      {commitError && (
        <div className="status-row status-err" style={{ marginTop:10 }}>
          <Icon.Warning/> {commitError}
        </div>
      )}

      {/* Action buttons */}
      <div style={{ display:'flex', gap:10, marginTop:16, flexWrap:'wrap' }}>
        <button className="btn btn-primary" disabled={!canCommit}
          onClick={async () => {
            setCommitError('');
            setCommitting(true);
            try {
              await onCommit(index, local);
            } catch (e) {
              setCommitError(e.message || 'Commit failed');
            } finally {
              setCommitting(false);
            }
          }}>
          {committing ? 'Creating...' : 'Create rule'}
        </button>
        <button className="btn btn-ghost" onClick={() => onRefine(index, local)}>
          Refine further
        </button>
        <button className="btn btn-ghost" style={{ color:'var(--red)', borderColor:'var(--red)' }}
          onClick={() => onDiscard(index)}>
          Discard
        </button>
      </div>
    </div>
  );
}

// ===============================================================================
// G6.1 -- STAGE 4 PANEL
// ===============================================================================

function Stage4Panel({ proposals, validations, onCommit, onRefine, onUpdate, onDiscard, data }) {
  const uncommitted = proposals.filter(p => !p.committed);

  if (proposals.length === 0) {
    return (
      <div className="status-row status-info" style={{ marginBottom:16 }}>
        No proposals to review. Go back to Step 3 and parse the AI output.
      </div>
    );
  }

  return (
    <div>
      <div style={{ display:'flex', alignItems:'center', gap:10, marginBottom:20 }}>
        <div className="page-title" style={{ marginBottom:0 }}>
          Review {proposals.length} rule proposal{proposals.length !== 1 ? 's' : ''}
        </div>
        {uncommitted.length > 0 && (
          <span className="badge badge-amber">{uncommitted.length} pending</span>
        )}
        {uncommitted.length === 0 && proposals.length > 0 && (
          <span className="badge badge-green">All committed</span>
        )}
      </div>

      {proposals.map((p, i) => (
        <ProposalReviewCard
          key={i}
          index={i}
          proposal={p}
          validation={validations[i] || { gaps:[], staleIds:[], warns:[] }}
          onCommit={onCommit}
          onRefine={onRefine}
          onUpdate={onUpdate}
          onDiscard={onDiscard}
          data={data}
        />
      ))}
    </div>
  );
}

// ===============================================================================
// G1.1 + G7.1 + G8 -- MAIN ASSISTANT SCREEN
// ===============================================================================

function AssistantScreen() {
  const { data, canEdit, upsertRecord, nextPk, navigate } = useApp();
  const dp = !canEdit
    ? { style:{ opacity:0.4, pointerEvents:'none' },
        title:'Set your steward identity in Settings to use the DQ Assistant' }
    : {};

  // Load persisted state
  const [stage,            setStage]           = useState(1);
  const [conversationMode, setConversationMode] = useState('business');
  const [ruleIntent,       setRuleIntent]       = useState('');
  const [selectedCdeIds,   setSelectedCdeIds]   = useState([]);
  const [extraTableIds,    setExtraTableIds]    = useState([]);
  const [cdeSearch,        setCdeSearch]        = useState('');
  const [builtPrompt,      setBuiltPrompt]      = useState('');
  const [contextSummary,   setContextSummary]   = useState(null);
  const [pasteText,        setPasteText]        = useState('');
  const [parseResult,      setParseResult]      = useState(null);
  const [proposals,        setProposals]        = useState([]);
  const [copyConfirmed,    setCopyConfirmed]    = useState(false);
  const [loaded,           setLoaded]           = useState(false);

  // Load on mount
  useEffect(() => {
    const s = loadAssistantState();
    if (s) {
      setRuleIntent(s.rule_intent);
      setSelectedCdeIds(s.cde_ids);
      setExtraTableIds(s.extra_table_ids);
      setConversationMode(s.conversation_mode || 'business');
      if (s.proposals && s.proposals.length > 0) {
        // Validate loaded proposals against current store
        const validated = s.proposals.map(p => ({
          ...p,
          _validation: validateProposal(p, data || {}),
        }));
        setProposals(validated);
        const hasUncommitted = validated.some(p => !p.committed);
        if (hasUncommitted) setStage(4);
      }
    }
    setLoaded(true);
  }, []);

  // Auto-save on intent/scope changes (debounced)
  const saveTimerRef = useRef(null);
  useEffect(() => {
    if (!loaded) return;
    if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
    saveTimerRef.current = setTimeout(() => {
      saveAssistantState({
        rule_intent:       ruleIntent,
        cde_ids:           selectedCdeIds,
        extra_table_ids:   extraTableIds,
        conversation_mode: conversationMode,
        proposals:         proposals,
      });
    }, 800);
    return () => clearTimeout(saveTimerRef.current);
  }, [ruleIntent, selectedCdeIds, extraTableIds, conversationMode, loaded]);

  // Immediate save on proposals change
  useEffect(() => {
    if (!loaded) return;
    saveAssistantState({
      rule_intent:       ruleIntent,
      cde_ids:           selectedCdeIds,
      extra_table_ids:   extraTableIds,
      conversation_mode: conversationMode,
      proposals,
    });
  }, [proposals, loaded]);

  // CDE suggestions (debounced)
  const [suggestions, setSuggestions] = useState([]);
  const suggTimerRef = useRef(null);
  useEffect(() => {
    if (suggTimerRef.current) clearTimeout(suggTimerRef.current);
    suggTimerRef.current = setTimeout(() => {
      setSuggestions(suggestCdes(ruleIntent, data));
    }, 300);
    return () => clearTimeout(suggTimerRef.current);
  }, [ruleIntent, data]);

  // Compute validations for proposals
  const validations = proposals.map(p => validateProposal(p, data || {}));

  const handleCdeToggle = (id) => {
    setSelectedCdeIds(prev =>
      prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]
    );
  };

  const handleExtraTableToggle = (id) => {
    setExtraTableIds(prev =>
      prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]
    );
  };

  const handleBuild = () => {
    if (!ruleIntent || ruleIntent.trim().length < 10 || !data) return;
    const result = buildAssistantPrompt(
      ruleIntent, selectedCdeIds, extraTableIds, conversationMode, data
    );
    setBuiltPrompt(result.promptText);
    setContextSummary({ ...result.contextSummary, characterCount: result.characterCount });
    setCopyConfirmed(false);
    setStage(2);
  };

  const handleCopy = () => {
    copyToClipboard(builtPrompt, () => {
      setCopyConfirmed(true);
      setTimeout(() => setCopyConfirmed(false), 3000);
    }, () => {});
  };

  const handleParse = () => {
    const result = parseProposals(pasteText);
    setParseResult(result);
    if (result.proposals && result.proposals.length > 0) {
      const withValidation = result.proposals.map(p => ({
        ...p,
        _validation: validateProposal(p, data || {}),
      }));
      setProposals(prev => {
        const uncommitted = prev.filter(p => !p.committed);
        // Merge: keep committed ones, replace uncommitted with newly parsed
        const committed   = prev.filter(p => p.committed);
        return [...committed, ...withValidation];
      });
      setStage(4);
    }
  };

  const handleAddContextCopy = (tableIds) => {
    const prompt = buildSupplementaryPrompt(tableIds, data);
    copyToClipboard(prompt, () => {}, () => {});
  };

  const handleCommit = (proposalIndex, proposal) => {
    if (!data || !canEdit) return;

    const ruleId  = nextPk('data_quality_rule');
    const allocId = nextPk('data_quality_rule_allocation');

    upsertRecord('data_quality_rule', {
      data_quality_rule_id: ruleId,
      rule_name:            proposal.rule_name,
      rule_explanation:     proposal.rule_narrative || proposal.rule_explanation || '',
      sql_code:             proposal.sql_code || '',
      sql_code_sample:      proposal.sql_code_sample || '',
      source_code_link:     '',
      automated:            proposal.automated !== false,
      retiring_timestamp:   null,
    });

    upsertRecord('data_quality_rule_allocation', {
      data_quality_rule_allocation_id: allocId,
      data_quality_rule_id:            ruleId,
      critical_data_element_id:        proposal.cde_id,
      quality_dimension_id:            proposal.quality_dimension_id,
      bumper_value:                    proposal.bumper_value,
      frequency:                       proposal.frequency || 'daily',
      retiring_timestamp:              null,
    });

    setProposals(prev => prev.map((p, i) =>
      i === proposalIndex
        ? { ...p, committed: true, _createdRuleId: ruleId, _createdAllocId: allocId }
        : p
    ));
  };

  const handleRefine = (proposalIndex, proposal) => {
    const v = validateProposal(proposal, data || {});
    const gaps = [...v.gaps, ...v.staleIds];
    const prompt = buildRefinementPrompt(proposal, gaps.length > 0 ? gaps : ['Please review and improve the proposal']);
    copyToClipboard(prompt, () => {}, () => {});
    setPasteText('');
    setParseResult(null);
    setStage(3);
  };

  const handleUpdateProposal = (index, updated) => {
    setProposals(prev => prev.map((p, i) => i === index ? { ...updated } : p));
  };

  const handleDiscardProposal = (index) => {
    if (window.confirm('Discard this proposal?')) {
      setProposals(prev => prev.filter((_, i) => i !== index));
    }
  };

  const handleStartNew = () => {
    if (window.confirm('Start a new conversation? This will clear your current rule and any uncommitted proposals.')) {
      clearAssistantState();
      setStage(1);
      setRuleIntent('');
      setSelectedCdeIds([]);
      setExtraTableIds([]);
      setConversationMode('business');
      setCdeSearch('');
      setBuiltPrompt('');
      setContextSummary(null);
      setPasteText('');
      setParseResult(null);
      setProposals([]);
      setCopyConfirmed(false);
    }
  };

  const accentColor = 'var(--accent)';

  return (
    <div className="fade-in">
      {/* Title row */}
      <div style={{ display:'flex', alignItems:'flex-start', justifyContent:'space-between', marginBottom:8 }}>
        <div>
          <div className="page-title">DQ Assistant</div>
          <div className="page-sub">
            Define quality rules with AI help. Build a prompt, copy to your AI tool, paste the result back.
          </div>
        </div>
        <button className="btn btn-ghost" style={{ fontSize:12, marginTop:4 }}
          onClick={handleStartNew}>
          Start new
        </button>
      </div>

      {/* Read-only gate */}
      {!canEdit && (
        <div className="status-row status-warn" style={{ marginBottom:20 }}>
          <Icon.Warning/>
          Read-only mode -- set your steward identity in Settings to use the DQ Assistant.
        </div>
      )}

      {/* Stage indicator */}
      <StageIndicator stage={stage} onNavigateStage={setStage}/>

      <div {...dp}>
        {/* ---- STAGE 1: DEFINE ---- */}
        {stage >= 1 && (
          <div style={{ opacity: stage === 1 ? 1 : 0.5, pointerEvents: stage === 1 ? 'auto' : 'none' }}>
            <div className="card" style={{ borderColor: stage === 1 ? accentColor : 'var(--border)', marginBottom:24 }}>
              <div className="card-title">
                <span className="dot" style={{ background: stage === 1 ? accentColor : 'var(--text3)' }}/>
                1 &ndash; Define the rule
              </div>
              {stage === 1 && (
                <Stage1Panel
                  conversationMode={conversationMode}
                  onModeChange={setConversationMode}
                  ruleIntent={ruleIntent}
                  onRuleIntentChange={setRuleIntent}
                  selectedCdeIds={selectedCdeIds}
                  onCdeToggle={handleCdeToggle}
                  extraTableIds={extraTableIds}
                  onExtraTableToggle={handleExtraTableToggle}
                  suggestions={suggestions}
                  cdeSearch={cdeSearch}
                  onCdeSearch={setCdeSearch}
                  data={data || {}}
                  onBuild={handleBuild}
                  promptBuilt={!!builtPrompt}
                />
              )}
              {stage > 1 && ruleIntent && (
                <div style={{ fontSize:13, color:'var(--text2)', fontStyle:'italic',
                  display:'flex', alignItems:'center', gap:10 }}>
                  <span className="badge badge-green"><Icon.Check/> Done</span>
                  "{ruleIntent.length > 80 ? ruleIntent.substring(0, 80) + '...' : ruleIntent}"
                </div>
              )}
            </div>
          </div>
        )}

        {/* ---- STAGE 2: PROMPT ---- */}
        {stage >= 2 && (
          <div style={{ opacity: stage === 2 ? 1 : 0.5, pointerEvents: stage === 2 ? 'auto' : 'none' }}>
            <div className="card" style={{ borderColor: stage === 2 ? accentColor : 'var(--border)', marginBottom:24 }}>
              <div className="card-title">
                <span className="dot" style={{ background: stage === 2 ? accentColor : 'var(--text3)' }}/>
                2 &ndash; Copy prompt to AI
              </div>
              {stage === 2 && (
                <Stage2Panel
                  builtPrompt={builtPrompt}
                  contextSummary={contextSummary}
                  onCopy={handleCopy}
                  copyConfirmed={copyConfirmed}
                  onBack={() => setStage(1)}
                />
              )}
              {stage > 2 && (
                <div style={{ fontSize:13, color:'var(--text2)', display:'flex', alignItems:'center', gap:10 }}>
                  <span className="badge badge-green"><Icon.Check/> Done</span>
                  Prompt copied to clipboard
                </div>
              )}
            </div>
          </div>
        )}

        {/* ---- STAGE 3: PASTE ---- */}
        {stage >= 3 && (
          <div style={{ opacity: stage === 3 ? 1 : 0.5, pointerEvents: stage === 3 ? 'auto' : 'none' }}>
            <div className="card" style={{ borderColor: stage === 3 ? accentColor : 'var(--border)', marginBottom:24 }}>
              <div className="card-title">
                <span className="dot" style={{ background: stage === 3 ? accentColor : 'var(--text3)' }}/>
                3 &ndash; Paste AI output
              </div>
              {stage === 3 && (
                <Stage3Panel
                  pasteText={pasteText}
                  onPasteChange={setPasteText}
                  onParse={handleParse}
                  parseResult={parseResult}
                  onAddContextCopy={handleAddContextCopy}
                  data={data || {}}
                  extraTableIds={extraTableIds}
                  onExtraTableToggle={handleExtraTableToggle}
                  onRegeneratePrompt={() => { setStage(2); }}
                />
              )}
              {stage > 3 && proposals.length > 0 && (
                <div style={{ fontSize:13, color:'var(--text2)', display:'flex', alignItems:'center', gap:10 }}>
                  <span className="badge badge-green"><Icon.Check/> Done</span>
                  {proposals.filter(p => !p.committed).length} proposal(s) ready to review
                </div>
              )}
            </div>
          </div>
        )}

        {/* ---- STAGE 4: COMMIT ---- */}
        {stage >= 4 && (
          <div>
            <div className="card" style={{ borderColor: stage === 4 ? accentColor : 'var(--border)' }}>
              <div className="card-title">
                <span className="dot" style={{ background: stage === 4 ? accentColor : 'var(--text3)' }}/>
                4 &ndash; Review and commit
              </div>
              <Stage4Panel
                proposals={proposals}
                validations={validations}
                onCommit={handleCommit}
                onRefine={handleRefine}
                onUpdate={handleUpdateProposal}
                onDiscard={handleDiscardProposal}
                data={data || {}}
              />
            </div>
          </div>
        )}

        {/* Show stage 3 prompt when on stage 2 (visible but muted) */}
        {stage === 2 && (
          <div style={{ opacity:0.4, pointerEvents:'none' }}>
            <div className="card" style={{ marginBottom:24 }}>
              <div className="card-title">
                <span className="dot" style={{ background:'var(--text3)' }}/>
                3 &ndash; Paste AI output
              </div>
              <div style={{ fontSize:12, color:'var(--text3)' }}>
                Complete Step 2 first -- copy the prompt and run your AI conversation.
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
